### ISSUE TITLE
Distributed training 

### ISSUE THREAD

**Issue by Hanqer** [kevin-ssy/ViP#3]
The script active a distributed training, but args.distributed is default as false. 
And the dist_init function is only support SLURM but not for pytorch DDP.

**Comment by kevin-ssy** [comment]
Maybe there're some environmental issues on your side as the script works well for me.

A quick suggestion is to use the original timm library and then copy-paste the model file of vip there for distributed training.

**Comment by Hanqer** [comment]
In the guidance of README, the example of the running scripts 'bash ./distributed_train.sh <job-name> <config-path> <num-gpus>', where ./distributed_train.sh is not exists. 
So I use the script in 'scripts' folder, but the 'distributed' flag in 'utils/init.py' line#217 is set as false by default. I change that, but in line#250, the distributed_utils.init_device does not exist too.
Is some errors in the release processing, or these are the inconsistency of my environments?
Thanks.

**Comment by kevin-ssy** [comment]
I correct the script. Try again?

**Comment by Hanqer** [comment]
It still has some errors, the function distributed_utils.init_device in utils/init.py does not exist. 
Do you want to call dist_init? But when changing it to dist_init, the key 'SLURM_PROCID' is not in os.environ will raise an error.

**Comment by kevin-ssy** [comment]
I just add the init_device function into distributed_utils. Please try again to see whether there're still bugs reported.
