### ISSUE TITLE
Any plans to share object detection models soon?

### ISSUE THREAD

**Issue by kilickaya** [kevin-ssy/ViP#4]
Hello! 

Thanks for your impressive work and sharing code and models for ImageNet. I wonder if there is any plan to release object detection models soon? 

Many thanks.

**Comment by kevin-ssy** [comment]
Yes, we're working on it now. Hopefully we will release it in a week.

**Comment by kevin-ssy** [comment]
> Hello!
> 
> Thanks for your impressive work and sharing code and models for ImageNet. I wonder if there is any plan to release object detection models soon?
> 
> Many thanks.

Hi, we just released the code for detection at https://github.com/yuexy/ViP-Object-Detection
