### ISSUE TITLE
The positional encoding d_w is only used in the self-attention in decoder?

### ISSUE THREAD

**Issue by nian-liu** [kevin-ssy/ViP#5]
Hi thanks for your nice work. Based on the paper, the positional encoding d_w is used in all three attention modules. However, from your code I found it is only used in the self-attention in decoder (Line 105 in the class Decoder in vip.py):

out = rearrange(out, "b (p k) c -> (b p) k c", p=P)
local_out = self.attn2(q=out, k=out, v=out, mask=mask, rel_pos=self.rel_pos)
out = out + self.drop_path(local_out)
out = out + self.drop_path(self.ffn2(out))

return rearrange(out, "(b p) k c -> b p k c", p=P)

**Comment by kevin-ssy** [comment]
Hi,

Thank you for your kind interest in our work.

We actually did some ablation studies on the sinusoidal absolute positional encoding after the first version of the paper was released on arxiv. The performance w/ and w/o the absolute positional encoding is similar (+-0.2% on ImageNet). So we just remove it in the released code based for simplicity.

BTW, it's better to reach me via email cuz I do not check GitHub issues quite frequently.
